WIP: UI Improvements
InvictusRMC/trustchain-superapp pull request #11
Opened 2020-04-15 13:15 UTC by InvictusRMC

2020-04-16 13:08 UTC, PJvanderLaan submitted a review, later dismissed
`JoinNetworkFragment.kt` will probably also have (some?) merge conflicts

2020-04-16 13:09 UTC, PJvanderLaan requested changes

2020-04-16 13:09 UTC, PJvanderLaan commented on currencyii/src/main/java/nl/tudelft/trustchain/currencyii/CoinCommunity.kt
> -        return newTransactionProposal
All changes to `CoinCommunity` need to be reverted

2020-04-17 10:41 UTC, PJvanderLaan approved these changes

2020-04-17 11:25 UTC, MKuijpers approved these changes

2020-04-17 11:26 UTC, merged